### ISSUE TITLE
New version of ruby-install breaks builds on EL5, EL6, MAC, ubuntu 12

### ISSUE THREAD

**Issue by rapenchukd** [tombruijn/chef-ruby-install#5]
Newest version of ruby-install just pushed now uses BASH function `declare -g`

This function was not added until BASH v4.2, thus is not available on pretty much any OS older than ~2 years by default.

**Comment by tombruijn** [comment]
@rapenchukd The test suite runs on ubuntu 12.04 just fine for me.

If a new version of ruby-install made it in comptible with your system please report it to the ruby-install repo. You can also select a older version in this cookbook by using the `git_ref` attribute for the default recipe.

**Comment by rapenchukd** [comment]
I did, it was fixed already. I was just posting more as an FYI.

**Comment by tombruijn** [comment]
@rapenchukd alright, wouldn't have hurt to link to the issue, but I found it. I reference not a git commit ref, but a version number for ruby-install. Unfortunately they have not released a new version in a while now, so I can't update the version number.

**Comment by rapenchukd** [comment]
Well, technically tags and releases are just aliases for commit refs. You can actually put the commit hash and your cookbook works
